### PR TITLE
Added support for assign variables from 'if' or 'begin' blocks.

### PR DESCRIPTION
**Pull request by pkuykendall**
This will properly format cases where a variable is being assigned from the result of an 'if' or 'begin' block.

### CODE REVIEW

**Comment by erniebrodeur** [comment]
Hey @pkuykendall, thanks for these, I'll check them out.  If you add them to the bloated example.rb, as a simple way to spec them, I'd be really appreciative and more likely to pull them sooner.

Else it'll take me a bit to verify/test them.

**Comment by pkuykendall** [comment]
Sure thing, I'll get it added and pushed soon.

Thanks!

**Comment by pkuykendall** [comment]
Hey @erniebrodeur, I added a few tests for these recent additions.

Cheers!

**Comment by erniebrodeur** [comment]
Merged, built, released, thanks!

**Comment by pkuykendall** [comment]
Thanks!

**Pull request merged**
