### PR TITLE
Fix the bug that it cannot write file correctly

### PR DESCRIPTION
**Pull request by bachue**

### CODE REVIEW

**Comment by erniebrodeur** [comment]
So I don't see anything wrong here, I'm not sure what problem you are having.  Overwrite is working exactly how it should be, the specs are passing (it has one for this exact use case, here it is played out below by hand).

```
% cat overwrite.rb
def ugly
puts 'this'
if true
puts 'is ugly enough'
end
end

% ruby-beautify --overwrite overwrite.rb

% cat overwrite.rb
def ugly
	puts 'this'
	if true
		puts 'is ugly enough'
	end
end
```

Can you elaborate on the issue some more?

Thanks

**Comment by bachue** [comment]
@erniebrodeur OK. my issue is, I appended "-s" to the command to use spaces, e.g. `ruby-beautify -c 2 -s --overwrite app/models/site.rb`, but the result was it still used tabs.

**Comment by erniebrodeur** [comment]
That's more specific, you just did a PR without enough context.

I'll need to test for this case, I didn't realize it wasn't passing in options.  

It'll be a day or two.

**Comment by bachue** [comment]
@erniebrodeur OK, it will be better if you can do more test.

**Comment by erniebrodeur** [comment]
Thanks, I've pushed this.  Good find, I've added some tests (not exactly related to this) as well.

**Pull request merged**
